---
- name: "Manage local Linux users"
  tags: user.account.linux
  ansible.builtin.user:
    name: "{{ item['name'] | mandatory }}"
    system: "{{ item['system'] | default(omit, true) }}"
    uid: "{{ item['uid'] | default(omit, true) }}"
    group: "{{ item['group'] | default(omit, true) }}"
    groups: "{{ item['groups'] | default(omit, true) }}"
    append: "{{ item['append'] | default(omit, true) }}"
    authorization: "{{ item['authorization'] | default(omit, true) }}"
    comment: "{{ item['comment'] | default(omit, true) }}"
    shell: "{{ item['shell'] | default(omit, true) }}"
    home: "{{ item['home'] | default(omit, true) }}"
    create_home: "{{ item['create_home'] | default(omit, true) }}"
    move_home: "{{ item['move_home'] | default(omit, true) }}"
    expires: "{{ item['expires'] | default(omit, true) }}"
    umask: "{{ item['umask'] | default(omit, true) }}"
    skeleton: "{{ item['skeleton'] | default(omit, true) }}"
    non_unique: "{{ item['non_unique'] | default(omit, true) }}"
    generate_ssh_key: "{{ item['generate_ssh_key'] | default(omit, true) }}"
    ssh_key_bits: "{{ item['ssh_key_bits'] | default(omit, true) }}"
    ssh_key_comment: "{{ item['ssh_key_comment'] | default(omit, true) }}"
    ssh_key_file: "{{ item['ssh_key_file'] | default(omit, true) }}"
    ssh_key_passphrase: "{{ item['ssh_key_passphrase'] | default(omit, true) }}"
    ssh_key_type: "{{ item['ssh_key_type'] | default(omit, true) }}"
    force: "{{ item['force'] | default(omit, true) }}"
    remove: "{{ item['remove'] | default(omit, true) }}"
    role: "{{ item['role'] | default(omit, true) }}"
    hidden: "{{ item['hidden'] | default(omit, true) }}"
    local: "{{ item['local'] | default(omit, true) }}"
    login_class: "{{ item['login_class'] | default(omit, true) }}"
    password: "{{ lookup('template','password.ji2') | trim }}"
    password_expire_min: "{{ item['password_expire_min'] | default(omit, true) }}"
    password_expire_max: "{{ item['password_expire_max'] | default(omit, true) }}"
    password_lock: "{{ item['password_lock'] | default(omit, true) }}"
    update_password: "{{ item['update_password'] | default(omit, true) }}"
    profile: "{{ item['profile'] | default(omit, true) }}"
    seuser: "{{ item['seuser'] | default(omit, true) }}"
    state: "{{ item['state'] | default(omit, true) }}"
  loop: "{{ user_accounts | selectattr('dn','undefined') }}"
  loop_control:
    label: "{{ item['name'] }} state={{ item['state'] | default('present') }}"
  when: |-
    ansible_os_family == 'RedHat' or
    ansible_os_family == 'Debian'
  become: true
  no_log: "{{ user_account_nolog | default(true) }}"

- name: "Manage local Windows users"
  tags: user.account.windows
  ansible.windows.win_user:
    name: "{{ item['name'] | mandatory }}"
    account_disabled: "{{ item['account_disabled'] | default(omit, true) }}"
    account_locked: "{{ item['account_locked'] | default(omit, true) }}"
    description: "{{ item['description'] | default(omit, true) }}"
    fullname: "{{ item['fullname'] | default(omit, true) }}"
    groups: "{{ item['groups'] | default([], true) | join(',') }}"
    groups_action: "{{ item['groups_action'] | default(omit, true) }}"
    home_directory: "{{ item['home'] | default(omit, true) }}"
    login_script: "{{ item['shell'] | default(omit, true) }}"
    password: "{{ lookup('template','password.ji2') | trim }}"
    password_expired: "{{ item['password_expired'] | default(omit, true) }}"
    password_never_expires: "{{ item['password_never_expires'] | default(omit, true) }}"
    profile: "{{ item['profile'] | default(omit, true) }}"
    state: "{{ item['state'] | default(omit, true) }}"
    update_password: "{{ item['update_password'] | default(omit, true) }}"
    user_cannot_change_password: "{{ item['user_cannot_change_password'] | default(omit, true) }}"
  loop: "{{ user_accounts | selectattr('dn','undefined') }}"
  loop_control:
    label: "{{ item['name'] }} state={{ item['state'] | default('present') }}"
  when:
    - ansible_os_family == 'Windows'
  become: true
  no_log: "{{ user_account_nolog | default(true) }}"
