---
- name: "Manage users"
  ansible.builtin.user:
    name: "{{ item['name'] | mandatory }}"
    system: "{{ item['system'] | default(omit, true) }}"
    uid: "{{ item['uid'] | default(omit, true) }}"
    group: "{{ item['group'] | default(omit, true) }}"
    groups: "{{ item['groups'] | default(omit, true) }}"
    append: "{{ item['append'] | default(omit, true) }}"
    comment: "{{ item['comment'] | default(omit, true) }}"
    shell: "{{ item['shell'] | default(omit, true) }}"
    home: "{{ item['home'] | default(omit, true) }}"
    create_home: "{{ item['create_home'] | default(omit, true) }}"
    skeleton: "{{ item['skeleton'] | default(omit, true) }}"
    non_unique: "{{ item['non_unique'] | default(omit, true) }}"
    generate_ssh_key: "{{ item['generate_ssh_key'] | default(omit, true) }}"
    ssh_key_bits: "{{ item['ssh_key_bits'] | default(omit, true) }}"
    ssh_key_comment: "{{ item['ssh_key_comment'] | default(omit, true) }}"
    ssh_key_file: "{{ item['ssh_key_file'] | default(omit, true) }}"
    ssh_key_passphrase: "{{ item['ssh_key_passphrase'] | default(omit, true) }}"
    ssh_key_type: "{{ item['ssh_key_type'] | default(omit, true) }}"
    force: "{{ item['force'] | default(omit, true) }}"
    state: "{{ item['state'] | default(omit, true) }}"
    update_password: "{{ item['update_password'] | default(omit, true) }}"
    password: "{{ lookup('template','password.ji2') | trim }}"
    password_lock: "{{ item['password_lock'] | default(omit, true) }}"
  loop: "{{ user_accounts }}"
  loop_control:
    label: "{{ item['name'] }} state={{ item['state'] | default('present') }}"
  no_log: "{{ user_account_log | default(true) }}"
