---
- name: "Manage bash aliases"
  tags:
    - user.bash
    - user.bash.alias
  ansible.builtin.lineinfile:
    create: true
    dest: "{{ item[0]['dest'] | default('') }}.bash_aliases"
    line: "alias {{ item[1] }}"
    owner: "{{ item[0]['owner'] | default(omit) }}"
    group: "{{ item[0]['group'] | default(omit) }}"
    mode: "{{ item[0]['mode'] | default(omit) }}"
    setype: "{{ item[0]['setype'] | default(omit) }}"
  loop: "{{ user_bashes | subelements('aliases') }}"
  loop_control:
    label: "{{ item[1] }} file={{ item[0]['dest'] | default('') }}.bash_aliases"

- name: "Manage bash PATH"
  tags:
    - user.bash
    - user.bash.path
  ansible.builtin.lineinfile:
    create: true
    dest: "{{ item[0]['dest'] | default('') }}.bash_profile"
    line: "{{ item[1] }}"
    owner: "{{ item[0]['owner'] | default(omit) }}"
    group: "{{ item[0]['group'] | default(omit) }}"
    mode: "{{ item[0]['mode'] | default(omit) }}"
    setype: "{{ item[0]['setype'] | default(omit) }}"
  loop: "{{ user_bashes | subelements('paths') }}"
  loop_control:
    label: "{{ item[1] }} file={{ item[0]['dest'] | default('') }}.bash_profile"
