---
- name: "Manage groups"
  ansible.builtin.group:
    name: "{{ item['name'] | mandatory }}"
    gid: "{{ item['gid'] | default(omit, true) }}"
    system: "{{ item['system'] | default(omit, true) }}"
    state: "{{ item['state'] | default(omit, true) }}"
  loop: "{{ user_groups }}"
  loop_control:
    label: "{{ item['name'] }} state={{ item['state'] | default('present') }}"
  become: true
