---
- name: "Manage limit"
  community.general.pam_limits:
    backup: "{{ item['backup'] | default(omit) }}"
    comment: "{{ item['comment'] | default(omit) }}"
    dest: "{{ item['dest'] | default(omit) }}"
    domain: "{{ item['domain'] | mandatory }}"
    limit_item: "{{ item['limit_item'] | mandatory }}"
    limit_type: "{{ item['limit_type'] | mandatory }}"
    use_max: "{{ item['use_max'] | default(omit) }}"
    use_min: "{{ item['use_min'] | default(omit) }}"
    value: "{{ item['value'] | mandatory }}"
  loop: "{{ user_limits }}"
  loop_control:
    label: "{{ item['domain'] }} {{ item['limit_type'] }} {{ item['limit_item'] }} {{ item['value'] }}"
  when: |-
    ansible_os_family == 'RedHat' or
    ansible_os_family == 'Debian'
  become: true
