---
- name: "Manage groups"
  tags:
    - user
    - user.group
  ansible.builtin.import_tasks: group.yaml

- name: "Manage user's account"
  tags:
    - user
    - user.account
  ansible.builtin.import_tasks: account.yaml

- name: "Manage user's home directory"
  tags:
    - user
    - user.homedir
  ansible.builtin.include_tasks: homedir.yaml
  loop: "{{ user_accounts | json_query(user_query_homedir) }}"
  loop_control:
    label: "{{ item }}"

- name: "Manage user's sshkeys"
  tags:
    - user
    - user.sshkeys
  ansible.builtin.import_tasks: sshkeys.yaml

- name: "Manage sudoers"
  tags:
    - user
    - user.sudoers
  ansible.builtin.import_tasks: sudoers.yaml
