---
- name: "Manage groups"
  tags:
    - user
    - user.group
  ansible.builtin.import_tasks: group.yaml

- name: "Manage user's account"
  tags:
    - user
    - user.account
  ansible.builtin.import_tasks: account.yaml

- name: "Manage user's home directory"
  tags:
    - user
    - user.homedir
  ansible.builtin.include_tasks: homedir.yaml
  loop: "{{ user_accounts | selectattr('dn','defined') }}"
  loop_control:
    label: "{{ item['dn'] }} homedir={{ item['attributes']['homeDirectory'] }}"
  when: |
    item['create_home'] is defined and
    item['create_home'] | bool

- name: "Manage user's sshkeys"
  tags:
    - user
    - user.sshkeys
  ansible.builtin.import_tasks: sshkeys.yaml

- name: "Manage sudoers"
  tags:
    - user
    - user.sudoers
  ansible.builtin.import_tasks: sudoers.yaml
