---
- name: "Manage sudoers"
  tags:
    - user
    - user.sudoers
  ansible.builtin.import_tasks: sudoers.yaml

- name: "Manage groups"
  tags:
    - user
    - user.group
  ansible.builtin.import_tasks: group.yaml

- name: "Manage user's account"
  tags:
    - user
    - user.account
  ansible.builtin.import_tasks: account.yaml

- name: "Manage user's in ldap"
  tags:
    - user
    - user.ldap
  ansible.builtin.import_tasks: ldap.yaml
  when: user_accounts | selectattr('dn','defined') | length > 0

- name: "Manage user's home directory"
  tags:
    - user
    - user.homedir
  ansible.builtin.include_tasks: homedir.yaml
  loop: "{{ user_accounts | json_query(user_query_homedir) }}"
  loop_control:
    label: "{{ item }}"
  when: |-
    ansible_os_family == 'RedHat' or
    ansible_os_family == 'Debian'

- name: "Manage user's sshkeys"
  tags:
    - user
    - user.sshkeys
  ansible.builtin.import_tasks: sshkeys.yaml

- name: "Manage user's limits"
  tags:
    - user
    - user.limit
  ansible.builtin.import_tasks: limit.yaml

- name: "Manage user's bash PATH and aliases"
  tags:
    - user
    - user.bash
  ansible.builtin.import_tasks: bash.yaml
