---
- name: "Manage ssh public key in authorized keys"
  tags: user.sshkeys.authorized
  ansible.posix.authorized_key:
    key:
      "{% if item[1]['key'] is match('ssh-.{256}') %}\
      {{ item[1]['key'] }}\
      {% else %}\
      {{ lookup('file', item[1]['key'], errors='ignore') }}\
      {% endif %}"
    user: "{{ item[0]['name'] }}"
    state: "{{ item[1]['state'] | default(omit, true) }}"
  loop: "{{ user_accounts | subelements('authorized_keys', skip_missing=True) }}"
  loop_control:
    label: "{{ item[0]['name'] }}"

- name: "Copy ssh keys"
  tags: user.sshkeys.private
  ansible.builtin.copy:
    src: "{{ item[1] }}"
    dest: "~{{ item[0]['name'] }}/.ssh/{{ item[1] | basename }}"
    owner: "{{ item[0]['name'] }}"
    group: "{{ item[0]['group'] | default(omit) }}"
    mode: preserve
  loop: "{{ user_accounts | subelements('ssh_keys', skip_missing=True) }}"
  loop_control:
    label: "{{ item[0]['name'] }} {{ item[1] }}"
