---
- name: "Manage sudoers"
  ansible.builtin.lineinfile:
    path: "/etc/{{ (item[0]['file'] == 'sudoers') | ternary(item[0]['file'],'sudoers.d/'+item[0]['file']) }}"
    line: >-
      {{ item[0]['for'] }} {{ item[0]['hosts'] }}
      =
      ({{ item[1]['user'] }}:{{ item[1]['group'] }})
      {{ item[1]['password'] | ternary('PASSWD:','NOPASSWD:') }} {{ item[1]['cmd'] }}
    owner: root
    group: root
    mode: 0400
    create: true
    state: "{{ item[0]['state'] | default(omit) }}"
  loop: "{{ user_sudoers | subelements('runas') }}"
  loop_control:
    label: "{{ item[0]['state'] | default('present') }} user={{ item[1]['user'] }} command={{ item[1]['cmd'] }}"
