---
- name: "Manage sudoers"
  ansible.builtin.lineinfile:
    path: >-
      /etc/{{ (item[0]['file'] == 'sudoers')
      | ternary(item[0]['file'], 'sudoers.d/' + item[0]['file']) }}
    regexp: "^#?{{ item[0]['from'] }}"
    line: >-
      {{ item[0]['from'] }} {{ item[0]['hosts'] }}
      =
      ({{ item[1]['user'] }}:{{ item[1]['group'] }})
      {{ item[1]['password']
      | ternary('PASSWD:', 'NOPASSWD:') }} {{ item[1]['cmd'] }}
    owner: "{{ user_sudoers_config['owner'] }}"
    group: "{{ user_sudoers_config['group'] }}"
    mode: "{{ user_sudoers_config['mode'] }}"
    setype: "{{ user_sudoers_config['setype'] }}"
    create: true
    state: "{{ item[0]['state'] | default(omit) }}"
  loop: "{{ user_sudoers | subelements('runas') }}"
  loop_control:
    label: >-
      {{ item[0]['state'] | default('present') }}
      file={{ item[0]['file'] }}
      from={{ item[0]['from'] }} command={{ item[1]['cmd'] }}
  when: |-
    ansible_os_family == 'RedHat' or
    ansible_os_family == 'Debian'
  become: true
